#!/usr/bin/env python3
"""
Configure Frontend
Sets up the frontend environment variables for the CML deployment.
This script should run before the frontend build to ensure proper API configuration.
"""

import os
import sys
import logging
from pathlib import Path

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(os.environ.get("PROJECT_ROOT", "/home/cdsw"))
FRONTEND_DIR = PROJECT_ROOT / "6_frontend"


def get_backend_api_url() -> str:
    """Determine the backend API URL based on environment."""
    # Check if explicitly configured
    api_url = os.environ.get("NEXT_PUBLIC_API_URL", "")
    if api_url:
        logger.info(f"Using configured NEXT_PUBLIC_API_URL: {api_url}")
        return api_url

    # Try to get actual URL from CML API
    cdsw_domain = os.environ.get("CDSW_DOMAIN", "")
    project_id = os.environ.get("CDSW_PROJECT_ID", "")

    if cdsw_domain and project_id:
        try:
            import cmlapi
            client = cmlapi.default_client()
            apps = client.list_applications(project_id=project_id)

            # Find the Credit Risk API application (prefer latest version)
            api_apps = [app for app in apps.applications if app.subdomain.startswith("credit-api")]
            if api_apps:
                # Sort by name to get latest version
                api_apps.sort(key=lambda a: a.name, reverse=True)
                subdomain = api_apps[0].subdomain
                api_url = f"https://{subdomain}.{cdsw_domain}/api"
                logger.info(f"Found API application: {api_apps[0].name} -> {api_url}")
                return api_url
        except Exception as e:
            logger.warning(f"Could not query CML API: {e}")

        # Fallback to simple pattern (may not work)
        backend_subdomain = "credit-api"
        api_url = f"https://{backend_subdomain}.{cdsw_domain}/api"
        logger.info(f"Constructed API URL from CML environment: {api_url}")
        return api_url

    # Fallback for local development
    api_url = "http://localhost:8000/api"
    logger.info(f"Using default local API URL: {api_url}")
    return api_url


def write_env_file(api_url: str):
    """Write the .env.local file for the frontend."""
    env_file = FRONTEND_DIR / ".env.local"

    env_content = f"""# Frontend Environment Variables
# Auto-generated by 0_setup/configure_frontend.py
# Manual changes will be overwritten during setup

NEXT_PUBLIC_API_URL={api_url}
"""

    with open(env_file, "w") as f:
        f.write(env_content)

    logger.info(f"Written frontend configuration to {env_file}")


def main():
    """Configure frontend environment."""
    print("\n" + "=" * 60)
    print("Credit Risk Platform - Frontend Configuration")
    print("=" * 60)

    # Check if frontend directory exists
    if not FRONTEND_DIR.exists():
        logger.error(f"Frontend directory not found: {FRONTEND_DIR}")
        return 1

    # Get API URL
    api_url = get_backend_api_url()

    # Write configuration
    write_env_file(api_url)

    print("\nConfiguration Summary:")
    print(f"  Frontend Directory: {FRONTEND_DIR}")
    print(f"  API URL: {api_url}")

    # Show CML environment info if available
    cdsw_domain = os.environ.get("CDSW_DOMAIN", "")
    if cdsw_domain:
        print(f"\nCML Environment Detected:")
        print(f"  Domain: {cdsw_domain}")
        print(f"  Project: {os.environ.get('CDSW_PROJECT', 'N/A')}")
        print(f"  Backend App: credit-api.{cdsw_domain}")
        print(f"  Frontend App: credit-app.{cdsw_domain}")

    print("\n" + "=" * 60)
    print("[SUCCESS] Frontend configuration complete!")
    print("=" * 60)

    return 0


if __name__ == "__main__":
    main()
